# App Name
spring.application.name=SkillSynth

#PostgreSQL connection Personal DB
spring.datasource.url=jdbc:postgresql://localhost:5432/skillsynth
spring.datasource.username=postgres
spring.datasource.password=Seniortest123!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



